---
# note: mostly for convenience when ssh'ing to your server.
- name: add GEM_HOME to .bashrc
  lineinfile:
    dest: "{{ home_directory }}/.bashrc"
    insertafter: BOF
    regexp: ^export.GEM_HOME
    line: "export GEM_HOME={{ gem_home }}"
    state: present

- name: update PATH with $GEM_HOME/bin
  lineinfile:
    dest: "{{ home_directory }}/.bashrc"
    insertafter: BOF
    regexp: ^export.PATH=.GEM_HOME
    line: "export PATH={{ gem_home }}/bin:$PATH"
    state: present

- name: execute bundler
  shell: chdir="{{ build_path }}" bundle install --path='{{ shared_path }}/vendor/bundle' --gemfile='./Gemfile' --deployment --binstubs='./bin'
  register: bundler
  changed_when: "'Installing' in bundler or 'Updating' in bundler or 'upgrade' in bundler"
  environment:
    GEM_HOME: "{{ gem_home }}"
    PATH: "{{ gem_home }}/bin:{{ ansible_env.PATH }}"

# - command: "diff -r -q {{ item.next }} {{ item.current }}"
#   register: migrate_output
#   with_items:
#     - { current: "{{ current_path }}/db/schema.rb", next: "{{ build_path }}/db/schema.rb" }
#     - { current: "{{ current_path }}/db/structure.sql", next: "{{ build_path }}/db/structure.sql" }
#     - "{{ migrate_diff_paths }}"
#   tags: test

# - debug:
#     var: migrate_output
#   tags: test

# - debug:
#     msg: "changed"
#   when: failed in migrate_output or force_migrate
#   tags: test

- name: migrate the database
  rake:
    path: "{{ build_path }}"
    bundled: yes
    command: 'db:migrate'
    diff_paths: "{{ migrate_diff_paths }}"
    force: "{{ force_migrate }}"
  environment:
    RAILS_ENV: "{{ rails_env }}"
  when: migrate

- name: precompile asset files if necessary
  rake:
    path: "{{ build_path }}"
    bundled: yes
    command: 'assets:precompile'
    diff_paths: "{{ asset_precompile_diff_paths }}"
    force: "{{ force_asset_compilation }}"
  environment:
    RAILS_ENV: "{{ rails_env }}"
  register: assets_changed
  when: compile_assets

- name: copy asset files when not changed
  shell: "cp -R {{ current_path }}/public/assets {{ build_path }}/public/assets"
  when: compile_assets and assets_changed is defined and not assets_changed.changed