---
- name: add GEM_HOME to .bashrc
  lineinfile:
    dest: "{{ home_directory }}/.bashrc"
    insertafter: BOF
    regexp: ^export.GEM_HOME
    line: "export GEM_HOME=$HOME/.gem"
    state: present

- name: update PATH with $GEM_HOME/bin
  lineinfile:
    dest: "{{ home_directory }}/.bashrc"
    insertafter: BOF
    regexp: ^export.PATH=.GEM_HOME
    line: "export PATH=$GEM_HOME/bin:$PATH"
    state: present

- name: execute bundler
  bundle:
    path: "{{ shared_path }}/vendor/bundle"
    gemfile: "{{ build_path }}/Gemfile"
    deployment: True
    binstubs: True

- name: migrate the database
  rake:
    path: "{{ build_path }}"
    bundled: yes
    command: 'db:migrate'
    diff_paths: "{{migrate_diff_paths}}"
    force: "{{force_migrate}}"
  environment:
    RAILS_ENV: "{{ rails_env }}"
  when: migrate

- name: precompile asset files if necessary
  rake:
    path: "{{ build_path }}"
    bundled: yes
    command: 'assets:precompile'
    diff_paths: "{{ asset_precompile_diff_paths }}"
    force: "{{ force_asset_compilation }}"
  environment:
    RAILS_ENV: "{{ rails_env }}"
  register: assets_changed
  when: compile_assets

- name: copy asset files when not changed
  shell: "cp -R {{ current_path }}/public/assets {{ build_path }}/public/assets"
  when: compile_assets and assets_changed is defined and not assets_changed.changed