---
- name: add GEM_HOME to .bashrc
  lineinfile:
    dest: "{{ home_directory }}/.bashrc"
    insertafter: BOF
    regexp: ^export.GEM_HOME
    line: "export GEM_HOME=$HOME/.gem"
    state: present

- name: update PATH with $GEM_HOME/bin
  lineinfile:
    dest: "{{ home_directory }}/.bashrc"
    insertafter: BOF
    regexp: ^export.PATH=.GEM_HOME
    line: "export PATH=$GEM_HOME/bin:$PATH"
    state: present

- name: execute bundler
  bundle:
    path: "{{ shared_path }}/vendor/bundle"
    gemfile: "{{ build_path }}/Gemfile"
    deployment: True
    binstubs: True

- name: migrate the database
  rake:
    path: "{{ build_path }}"
    rails_env: "{{ rails_env }}"
    current: "{{ current_path }}"
    bundled: yes
    migrate: yes
    force: $force_migrate
  when: migrate

- name: precompile asset files
  rake:
    path: "{{ build_path }}"
    rails_env: "{{ rails_env }}"
    current: "{{ current_path }}"
    bundled: yes
    assets: yes
    force: "{{ force_asset_compilation }}"
  when: compile_assets