---
- name: add GEM_HOME to .bashrc
  lineinfile:
    dest: "{{ home_directory }}/.bashrc"
    insertafter: BOF
    regexp: ^export.GEM_HOME
    line: "export GEM_HOME=$HOME/.gem"
    state: present

- name: update PATH with $GEM_HOME/bin
  lineinfile:
    dest: "{{ home_directory }}/.bashrc"
    insertafter: BOF
    regexp: ^export.PATH=.GEM_HOME
    line: "export PATH=$GEM_HOME/bin:$PATH"
    state: present

- name: execute bundler
  bundle:
    path: "{{ shared_path }}/vendor/bundle"
    gemfile: "{{ build_path }}/Gemfile"
    deployment: True
    binstubs: True

- name: migrate the database
  rake:
    path: "{{ build_path }}"
    rails_env: "{{ rails_env }}"
    bundled: yes
    command: 'db:migrate'
    diff_paths:
      - { current: "{{ current_path }}/db/schema.rb", next: "{{ build_path }}/db/schema.rb" }
      - { current: "{{ current_path }}/db/structure.sql", next: "{{ build_path }}/db/structure.sql" }
    force: $force_migrate
  when: migrate

- name: precompile asset files
  rake:
    path: "{{ build_path }}"
    rails_env: "{{ rails_env }}"
    bundled: yes
    command: 'assets:precompile'
    diff_paths:
      - { current: "{{ current_path }}/app/assets", next: "{{ build_path }}/app/assets" }
      - { current: "{{ current_path }}/vendor/assets", next: "{{ build_path }}/vendor/assets" }
      - { current: "{{ current_path }}/Gemfile.lock", next: "{{ build_path }}/Gemfile.lock" }
    force: $force_asset_compilation
  when: compile_assets